# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('cid', models.AutoField(db_column='Cid', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('fid', models.IntegerField(db_column='Fid', primary_key=True, serialize=False)),
                ('follower', models.CharField(blank=True, db_column='Follower', max_length=100, null=True)),
                ('followee', models.CharField(blank=True, db_column='Followee', max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Following',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('lid', models.AutoField(db_column='Lid', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, db_column='Pid', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pid', models.AutoField(db_column='Pid', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('ptid', models.IntegerField(db_column='PTid', primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(blank=True, db_column='Pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekInRest.Posts')),
            ],
            options={
                'managed': True,
                'db_table': 'Post_Tags',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tid', models.AutoField(db_column='Tid', primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, db_column='Tag', max_length=50, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, db_column='Photo', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=20, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=100, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('utid', models.IntegerField(db_column='UTid', primary_key=True, serialize=False)),
                ('tid', models.IntegerField(blank=True, db_column='Tid', null=True)),
                ('email', models.ForeignKey(blank=True, db_column='Email', null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekInRest.Users')),
            ],
            options={
                'managed': True,
                'db_table': 'User_Tags',
            },
        ),
        migrations.AddField(
            model_name='posttags',
            name='tid',
            field=models.ForeignKey(blank=True, db_column='Tid', null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekInRest.Tags'),
        ),
        migrations.AddField(
            model_name='comments',
            name='pid',
            field=models.ForeignKey(blank=True, db_column='Pid', null=True, on_delete=django.db.models.deletion.CASCADE, to='GeekInRest.Posts'),
        ),
    ]
