# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeekInRest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('GuestEmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='GeekInRest.Users')),
                ('HostEmail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to='GeekInRest.Users')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_column='TimeStamp', default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='likes',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_column='TimeStamp', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(blank=True, db_column='TimeStamp', default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(blank=True, db_column='TimeStamp', default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='Pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeekInRest.Posts'),
        ),
    ]
